# Generated by Django 3.2.8 on 2021-10-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211019_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
