# Generated by Django 3.2.8 on 2021-10-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='position_x',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='position_y',
            new_name='y',
        ),
    ]
