# Generated by Django 3.2.8 on 2021-10-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211027_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visit_time',
            field=models.IntegerField(default=0),
        ),
    ]
